dataset:
  ff_path: "/content/TEP_FaultFree_Training.RData"
  ft_path: "/content/TEP_Faulty_Training.RData"

data_windowing:
  window_size: 100
  stride: 5
  post_fault_start: 100         
  train_runs_start: 1
  train_runs_end: 35
  test_runs_start: 36
  test_runs_end: 55

training:
  epochs: 100
  batch:
    train: 128
    val: 256
    test: 256
  num_workers: 2
  seed: 42
  diffusion:
    enabled: true
    start_epoch: 3
    synth_ratio: 0.2      
    steps_infer: 24
    epochs: 20          
    width: 512
    depth: 3
    margin_gate_delta: 0.05

model:
  s: 16.0
  m: 0.15
  margin_type: "arc"
  per_class_margin_overrides:
    "0": 0.28
    "15": 0.28
  center_momentum: 0.95
  center_sep_K: 3
  center_sep_margin: 0.28
  center_pull_weights:
    "0": 2.5
    "15": 3.0
