dataset:
  ff_path: "/root/TEP_FaultFree_Training.RData"
  ft_path: "/root/TEP_Faulty_Training.RData"

data_windowing:
  window_size: 100
  stride: 5
  normal_train_start: 0
  normal_train_end: 240000
  normal_test_start: 244000
  normal_test_end: 250000
  post_fault_start: 100         
  train_runs_start: 1
  train_runs_end: 80
  test_runs_start: 100
  test_runs_end: 1

training:
  epochs: 100
  batch:
    train: 128
    val: 256
    test: 256
  num_workers: 2
  seed: 42
  diffusion:
    enabled: true
    start_epoch: 13
    synth_ratio: 0.2      
    steps_infer: 70
    epochs: 20      
    width: 512
    depth: 3
    margin_gate_delta: 0.05
    selected_faults: [3,9,15]
    export_per_class: 1000
    export_steps_infer: 150

model:
  s: 16.0
  m: 0.15
  margin_type: "arc"
  per_class_margin_overrides:
    "0": 0.28
    "15": 0.28
  center_momentum: 0.95
  center_sep_K: 3
  center_sep_margin: 0.28
  center_pull_weights:
    "0": 2.5
    "15": 3.0
